import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDownRight, ArrowRight } from "lucide-react";
import { CreditImage, SectionHead } from "@/components/AstroUI";
import { deepSpace, heroImage, missions, nebulas, planets } from "@/data/cosmos";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Parallax Observatory — Explore the Universe"},{name:"description",content:"An immersive, scientific journey through the Solar System, deep space, nebulae, black holes, and landmark missions."},{property:"og:title",content:"Parallax Observatory — Explore the Universe"},{property:"og:description",content:"An immersive digital observatory built around real astronomical imagery."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
function Home(){return <>
<section className="hero"><img src={heroImage.src} alt={heroImage.alt} className="hero-image"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow text-foreground/80">Digital observatory · Field 001</p><h1 className="hero-title">The universe<br/>is vast.</h1><p className="mt-5 max-w-md text-lg leading-7 text-foreground/80">And we are only beginning to understand it.</p><Link to="/deep-space" className="hero-link">Explore the cosmos <ArrowRight size={17}/></Link></div><div className="hero-stats">{[["13.8","Billion years · estimated age"],["~93 B","Light-years · observable diameter"],["≥100 B","Galaxies · estimate"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><a href="#begin" className="scroll-cue" aria-label="Continue exploring"><ArrowDownRight/></a></section>
<section id="begin" className="page-shell py-28"><SectionHead index="01" kicker="Orientation" title="A field guide to everything." copy="Move outward from our local star to structures whose light began traveling before Earth existed. Measurements are approximate and linked to primary scientific sources."/><div className="mt-20 grid gap-px bg-border md:grid-cols-3">{[["Solar System",planets[5].image,"Worlds shaped by heat, ice, gravity, and time.","/solar-system"],["Deep Space",deepSpace[1].image,"Galaxies colliding across hundreds of millions of light-years.","/deep-space"],["Nebulas",nebulas[1].image,"Stellar nurseries and the intricate remains of dead stars.","/nebulas"]].map(([name,image,copy,to])=><Link key={String(name)} to={to as "/solar-system"} className="group relative aspect-[3/4] overflow-hidden bg-background"><img src={(image as typeof heroImage).src} alt={(image as typeof heroImage).alt} loading="lazy" className="h-full w-full object-cover opacity-75 transition duration-700 group-hover:scale-[1.025] group-hover:opacity-100"/><div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><p className="eyebrow">Observation field</p><h3 className="mt-3 font-display text-4xl">{name as string}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-foreground/70">{copy as string}</p></div></Link>)}</div></section>
<section className="border-y border-border bg-surface py-28"><div className="page-shell"><SectionHead index="02" kicker="Solar system" title="One star. Eight planets. Countless worlds."/><div className="mt-16 grid items-center gap-10 lg:grid-cols-[1.2fr_1fr]"><CreditImage image={planets[6].image} className="aspect-[4/3]"/><div><p className="eyebrow">Featured world / Saturn</p><h3 className="mt-5 font-display text-6xl">A system within<br/>a system.</h3><p className="mt-6 max-w-lg leading-7 text-muted-foreground">Saturn's rings and more than a hundred known moons form an intricate laboratory of orbital dynamics, ice, atmosphere, and geology.</p><Link to="/solar-system" className="text-link mt-8">Enter the planetary explorer <ArrowRight size={16}/></Link></div></div></div></section>
<section className="page-shell py-28"><SectionHead index="03" kicker="Human reach" title="Machines at the frontier."/><div className="mt-16 border-t border-border">{missions.slice(0,3).map((m,i)=><Link key={m.name} to="/missions" className="group grid gap-4 border-b border-border py-7 md:grid-cols-[80px_1fr_1fr_auto] md:items-center"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><strong className="font-display text-2xl">{m.name}</strong><span className="text-sm text-muted-foreground">{m.destination}</span><ArrowRight className="transition-transform group-hover:translate-x-1"/></Link>)}</div></section>
</>}
