import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, Search, X } from "lucide-react";
import { useEffect, useState } from "react";

const nav = [["Solar System","/solar-system"],["Deep Space","/deep-space"],["Nebulas","/nebulas"],["Supernovas","/supernovas"],["Black Holes","/black-holes"],["Missions","/missions"],["Discoveries","/discoveries"]] as const;

export function SiteChrome({ children }: { children: React.ReactNode }) {
 const [menu,setMenu]=useState(false); const [search,setSearch]=useState(false); const [progress,setProgress]=useState(0);
 const path=useRouterState({select:s=>s.location.pathname});
 useEffect(()=>{setMenu(false); const on=()=>{const d=document.documentElement; setProgress(d.scrollHeight<=d.clientHeight?0:d.scrollTop/(d.scrollHeight-d.clientHeight)*100)}; on(); addEventListener("scroll",on,{passive:true}); return()=>removeEventListener("scroll",on)},[path]);
 return <><div className="fixed inset-x-0 top-0 z-50 h-px bg-border"><div className="h-full bg-stellar transition-[width]" style={{width:`${progress}%`}} /></div>
 <header className="fixed inset-x-0 top-px z-40 border-b border-border/60 bg-background/78 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1680px] items-center px-5 lg:px-10"><Link to="/" className="font-display text-lg tracking-normal text-foreground">PARALLAX <span className="text-muted-foreground">/ OBSERVATORY</span></Link><nav className="ml-auto hidden items-center gap-5 xl:flex">{nav.map(([n,to])=><Link key={to} to={to} className="nav-link" activeProps={{className:"nav-link text-foreground"}}>{n}</Link>)}</nav><button className="icon-button ml-auto xl:ml-5" onClick={()=>setSearch(true)} aria-label="Search"><Search size={17}/></button><button className="icon-button ml-2 xl:hidden" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<div className="fixed inset-0 z-30 bg-background px-6 pt-28 xl:hidden"><nav className="grid">{nav.map(([n,to],i)=><Link key={to} to={to} className="border-t border-border py-5 font-display text-3xl"><span className="mr-5 font-mono text-xs text-muted-foreground">0{i+1}</span>{n}</Link>)}</nav></div>}
 {search&&<SearchPanel close={()=>setSearch(false)}/>}<main>{children}</main><Footer/></>;
}
function SearchPanel({close}:{close:()=>void}){const [q,setQ]=useState(""); const matches=nav.filter(([n])=>n.toLowerCase().includes(q.toLowerCase())); useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==="Escape"&&close();addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[close]);return <div className="fixed inset-0 z-[60] bg-background/95 p-5 backdrop-blur-xl" role="dialog" aria-modal="true" aria-label="Search the observatory"><div className="mx-auto max-w-4xl pt-20"><button onClick={close} className="icon-button ml-auto flex" aria-label="Close search"><X/></button><label className="eyebrow" htmlFor="site-search">Search the observatory</label><input autoFocus id="site-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Planet, nebula, mission…" className="mt-5 w-full border-b border-border bg-transparent py-5 font-display text-4xl outline-none focus:border-stellar md:text-6xl"/><div className="mt-10">{matches.map(([n,to])=><Link key={to} to={to} onClick={close} className="flex border-t border-border py-5 text-xl">{n}<span className="ml-auto">↗</span></Link>)}</div></div></div>}
function Footer(){return <footer className="border-t border-border bg-surface px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1680px] gap-12 lg:grid-cols-[1.5fr_1fr_1fr]"><div><p className="font-display text-2xl">PARALLAX / OBSERVATORY</p><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">An independent digital observatory built to make primary astronomical imagery and science more explorable. Not affiliated with NASA, ESA, CSA, JPL, or STScI.</p></div><div><p className="eyebrow">Explore</p>{nav.slice(0,4).map(([n,to])=><Link key={to} to={to} className="mt-3 block text-sm text-muted-foreground hover:text-foreground">{n}</Link>)}</div><div><p className="eyebrow">Primary sources</p>{[["NASA Science","https://science.nasa.gov"],["ESA Science","https://www.esa.int/Science_Exploration"],["STScI","https://www.stsci.edu"],["NASA/JPL","https://www.jpl.nasa.gov"]].map(([n,u])=><a key={u} href={u} target="_blank" rel="noreferrer" className="mt-3 block text-sm text-muted-foreground hover:text-foreground">{n} ↗</a>)}</div></div><div className="mx-auto mt-14 flex max-w-[1680px] flex-col gap-2 border-t border-border pt-5 font-mono text-[10px] uppercase text-muted-foreground md:flex-row md:justify-between"><span>© 2026 Parallax Observatory</span><span>Imagery credited individually to its scientific source</span></div></footer>}
