/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlackHolesRouteImport } from './routes/black-holes'
import { Route as DeepSpaceRouteImport } from './routes/deep-space'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as NebulasRouteImport } from './routes/nebulas'
import { Route as SolarSystemRouteImport } from './routes/solar-system'
import { Route as SupernovasRouteImport } from './routes/supernovas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackHolesRoute = BlackHolesRouteImport.update({
  id: '/black-holes',
  path: '/black-holes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepSpaceRoute = DeepSpaceRouteImport.update({
  id: '/deep-space',
  path: '/deep-space',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulasRoute = NebulasRouteImport.update({
  id: '/nebulas',
  path: '/nebulas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemRoute = SolarSystemRouteImport.update({
  id: '/solar-system',
  path: '/solar-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SupernovasRoute = SupernovasRouteImport.update({
  id: '/supernovas',
  path: '/supernovas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/black-holes': typeof BlackHolesRoute
  '/deep-space': typeof DeepSpaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/missions': typeof MissionsRoute
  '/nebulas': typeof NebulasRoute
  '/solar-system': typeof SolarSystemRoute
  '/supernovas': typeof SupernovasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/black-holes': typeof BlackHolesRoute
  '/deep-space': typeof DeepSpaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/missions': typeof MissionsRoute
  '/nebulas': typeof NebulasRoute
  '/solar-system': typeof SolarSystemRoute
  '/supernovas': typeof SupernovasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/black-holes': typeof BlackHolesRoute
  '/deep-space': typeof DeepSpaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/missions': typeof MissionsRoute
  '/nebulas': typeof NebulasRoute
  '/solar-system': typeof SolarSystemRoute
  '/supernovas': typeof SupernovasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/black-holes'
    | '/deep-space'
    | '/discoveries'
    | '/missions'
    | '/nebulas'
    | '/solar-system'
    | '/supernovas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/black-holes'
    | '/deep-space'
    | '/discoveries'
    | '/missions'
    | '/nebulas'
    | '/solar-system'
    | '/supernovas'
  id:
    | '__root__'
    | '/'
    | '/black-holes'
    | '/deep-space'
    | '/discoveries'
    | '/missions'
    | '/nebulas'
    | '/solar-system'
    | '/supernovas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackHolesRoute: typeof BlackHolesRoute
  DeepSpaceRoute: typeof DeepSpaceRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  MissionsRoute: typeof MissionsRoute
  NebulasRoute: typeof NebulasRoute
  SolarSystemRoute: typeof SolarSystemRoute
  SupernovasRoute: typeof SupernovasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-holes': {
      id: '/black-holes'
      path: '/black-holes'
      fullPath: '/black-holes'
      preLoaderRoute: typeof BlackHolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-space': {
      id: '/deep-space'
      path: '/deep-space'
      fullPath: '/deep-space'
      preLoaderRoute: typeof DeepSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebulas': {
      id: '/nebulas'
      path: '/nebulas'
      fullPath: '/nebulas'
      preLoaderRoute: typeof NebulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system': {
      id: '/solar-system'
      path: '/solar-system'
      fullPath: '/solar-system'
      preLoaderRoute: typeof SolarSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supernovas': {
      id: '/supernovas'
      path: '/supernovas'
      fullPath: '/supernovas'
      preLoaderRoute: typeof SupernovasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackHolesRoute: BlackHolesRoute,
  DeepSpaceRoute: DeepSpaceRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  MissionsRoute: MissionsRoute,
  NebulasRoute: NebulasRoute,
  SolarSystemRoute: SolarSystemRoute,
  SupernovasRoute: SupernovasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
